Section:
    type: object
    config:
        description: "An Ibexa repository section."
        fields:
            id:
                type: "Int!"
                description: "The Section's unique ID."
            identifier:
                type: "String"
                description: "The Section's system identifier."
            name:
                type: "String"
                description: "The Section's name."
