parameters:
  ibexa.graphql.schema.content.field_name.override:
    id: id_
  ibexa.graphql.schema.content.mapping.field_definition_type:
    ibexa_author:
      value_type: "[AuthorFieldValue]"
      value_resolver: 'field !== null ? field.authors : null'
      input_type: '[AuthorInput]'
    ibexa_binaryfile:
      definition_type: BinaryFieldDefinition
      value_type: BinaryFileFieldValue
      input_type: BinaryFieldInput
    ibexa_boolean:
      definition_type: CheckboxFieldDefinition
      value_type: Boolean
      value_resolver: 'field !== null ? field.bool : null'
      input_type: Boolean
    ibexa_country:
      definition_type: CountryFieldDefinition
      value_type: String
      input_type: '[String]'
    ibexa_date:
      value_type: DateTime
      value_resolver: 'field !== null ? field.date : null'
      input_type: DateFieldInput
    ibexa_datetime:
      value_type: DateTime
      value_resolver: 'field !== null ? field.value : null'
      input_type: DateFieldInput
    ibexa_email:
      value_type: String
    ibexa_user:
      value_type: String
      value_resolver: 'field.id'
    ibexa_float:
      definition_type: FloatFieldDefinition
      value_type: Float
      value_resolver: 'field !== null ? field.value : null'
      input_type: Float
    ibexa_gmap_location:
      value_type: MapLocationFieldValue
      input_type: 'MapLocationFieldInput'
    ibexa_image:
      definition_type: BinaryFieldDefinition
      value_type: ImageFieldValue
      input_type: ImageFieldInput
    ibexa_imageasset:
      value_type: ImageFieldValue
      value_resolver: 'query("DomainImageAssetFieldValue", field)'
    ibexa_integer:
      definition_type: IntegerFieldDefinition
      value_type: Int
      value_resolver: 'field !== null ? field.value : null'
      input_type: Int
    ibexa_keyword:
      value_type: '[String]'
      value_resolver: 'field !== null ? field.values : null'
      input_type: '[String]'
    ibexa_media:
      definition_type: MediaFieldDefinition
      value_type: MediaFieldValue
      input_type: MediaFieldInput
    ibexa_object_relation:
      definition_type: RelationFieldDefinition
      value_type: RelationFieldValue
      input_type: Int
    ibexa_object_relation_list:
      definition_type: RelationListFieldDefinition
      value_type: RelationListFieldValue
      input_type: '[Int]'
    ibexa_richtext:
      value_type: RichTextFieldValue
      input_type: RichTextFieldInput
    ibexa_selection:
      definition_type: SelectionFieldDefinition
      input_type: '[Int]'
    ibexa_string:
      definition_type: TextLineFieldDefinition
      value_type: String
    ibexa_text:
      definition_type: TextBlockFieldDefinition
      value_type: String
    ibexa_url:
      value_type: UrlFieldValue
      input_type: UrlFieldInput
