services:

    EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory\CurrentSite:
        alias: Ibexa\GraphQL\ItemFactory\CurrentSite

    EzSystems\EzPlatformGraphQL\GraphQL\ItemFactory\RelatedContent:
        alias: Ibexa\GraphQL\ItemFactory\RelatedContent

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Author:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\Author

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Boolean:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\Boolean

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Country:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\Country

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\DateAndTime:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\DateAndTime

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Float:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\Float

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Email:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\Email

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Integer:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\Integer

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\ISBN:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\ISBN

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Keyword:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\Keyword

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\MapLocation:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\MapLocation

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Selection:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\MapLocation

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\TextBlock:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\TextBlock

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\TextLine:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\TextLine

    EzSystems\EzPlatformGraphQL\GraphQL\Mutation\InputHandler\FieldType\Url:
        alias: Ibexa\GraphQL\Mutation\InputHandler\FieldType\Url
