services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  Ibexa\GraphQL\Resolver\DomainContentMutationResolver:
    tags:
      - { name: overblog_graphql.mutation, alias: "CreateDomainContent", method: "createDomainContent" }
      - { name: overblog_graphql.mutation, alias: "DeleteDomainContent", method: "deleteDomainContent" }
      - { name: overblog_graphql.mutation, alias: "UpdateDomainContent", method: "updateDomainContent" }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Author:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Author\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezauthor' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\BinaryFile:
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezbinaryfile' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Boolean:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Checkbox\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezboolean' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Country:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Country\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezcountry' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Date:
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Date\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezdate' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\DateAndTime:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\Date'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\DateAndTime\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezdatetime' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Float:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Float\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezfloat' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Email:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\EmailAddress\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezemail' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Image:
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezimage' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Integer:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Integer\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezinteger' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\ISBN:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\ISBN\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezisbn' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Keyword:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Keyword\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezkeyword' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\MapLocation:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\MapLocation\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezgmaplocation' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Media:
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezmedia' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Relation:
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Relation\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezobjectrelation' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\RelationList:
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\RelationList\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezobjectrelationlist' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText:
    arguments:
      $inputConverters:
        html: '@Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText\HtmlRichTextConverter'
        markdown: '@Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText\MarkdownRichTextConverter'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezrichtext' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText\HtmlRichTextConverter:
    arguments:
      $xhtml5Converter: '@ibexa.richtext.converter.input.xhtml5'
    tags:
      - { name: ezplatform_graphql.richtext_input_converter, format: html }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText\MarkdownRichTextConverter:
    arguments:
      $xhtml5Converter: '@ibexa.richtext.converter.input.xhtml5'
    tags:
      - { name: ezplatform_graphql.richtext_input_converter, format: markdown }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Selection:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Selection\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezselection' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\TextBlock:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\TextBlock\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'eztext' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\TextLine:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\TextLine\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezstring' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Url:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Url\Type'
    tags:
      - { name: ezplatform_graphql.fieldtype_input_handler, fieldtype: 'ezurl' }
