services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false

  Ibexa\GraphQL\Resolver\DomainContentMutationResolver:
    tags:
      - { name: overblog_graphql.mutation, alias: "CreateDomainContent", method: "createDomainContent" }
      - { name: overblog_graphql.mutation, alias: "DeleteDomainContent", method: "deleteDomainContent" }
      - { name: overblog_graphql.mutation, alias: "UpdateDomainContent", method: "updateDomainContent" }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Author:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Author\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_author' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\BinaryFile:
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_binaryfile' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Boolean:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Checkbox\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_boolean' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Country:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Country\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_country' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Date:
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Date\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_date' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\DateAndTime:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\Date'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\DateAndTime\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_datetime' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Float:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Float\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_float' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Email:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\EmailAddress\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_email' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Image:
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_image' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Integer:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Integer\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_integer' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\ISBN:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\ISBN\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_isbn' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Keyword:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Keyword\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_keyword' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\MapLocation:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\MapLocation\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_gmap_location' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Media:
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_media' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Relation:
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Relation\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_object_relation' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\RelationList:
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\RelationList\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_object_relation_list' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText:
    arguments:
      $inputConverters:
        html: '@Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText\HtmlRichTextConverter'
        markdown: '@Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText\MarkdownRichTextConverter'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_richtext' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText\HtmlRichTextConverter:
    arguments:
      $xhtml5Converter: '@ibexa.richtext.converter.input.xhtml5'
    tags:
      - { name: ibexa.graphql.richtext.input.converter, format: html }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\RichText\MarkdownRichTextConverter:
    arguments:
      $xhtml5Converter: '@ibexa.richtext.converter.input.xhtml5'
    tags:
      - { name: ibexa.graphql.richtext.input.converter, format: markdown }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Selection:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Selection\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_selection' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\TextBlock:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\TextBlock\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_text' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\TextLine:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\TextLine\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_string' }

  Ibexa\GraphQL\Mutation\InputHandler\FieldType\Url:
    class: 'Ibexa\GraphQL\Mutation\InputHandler\FieldType\FromHash'
    arguments:
      $fieldType: '@Ibexa\Core\FieldType\Url\Type'
    tags:
      - { name: ibexa.graphql.field_type.input.handler, fieldtype: 'ibexa_url' }
